2024-03-16 20:54:30,865 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
2024-03-16 20:54:31,192 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
2024-03-16 20:54:34,132 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
2024-03-16 21:03:29,176 INFO: User manolo authenticated successfully
2024-03-16 21:03:29,176 INFO: JWT token generated for user ID: 10
2024-03-16 21:04:42,153 INFO: User manolo authenticated successfully
2024-03-16 21:04:42,154 INFO: JWT token generated for user ID: 10
2024-03-16 21:04:53,756 INFO: User manolo authenticated successfully
2024-03-16 21:04:53,758 INFO: JWT token generated for user ID: 10
2024-03-16 21:04:54,875 INFO: User manolo authenticated successfully
2024-03-16 21:04:54,876 INFO: JWT token generated for user ID: 10
2024-03-16 21:08:39,123 INFO: User manolo authenticated successfully
2024-03-16 21:08:39,124 INFO: JWT token generated for user ID: 10
2024-03-16 21:18:21,350 INFO: User manolo authenticated successfully
2024-03-16 21:18:21,351 INFO: JWT token generated for user ID: 10
2024-03-16 21:21:32,291 ERROR: Exception on /ejercicios [GET]
Traceback (most recent call last):
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask\views.py", line 110, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)  # type: ignore[no-any-return]
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_restful\__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 167, in decorator
    verify_jwt_in_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 94, in verify_jwt_in_request
    jwt_data, jwt_header, jwt_location = _decode_jwt_from_request(
  File "C:\Users\blood\OneDrive\Escritorio\arq_sec\misw202411_grupo22\sportapp-2\venv\lib\site-packages\flask_jwt_extended\view_decorators.py", line 358, in _decode_jwt_from_request
    raise NoAuthorizationError(errors[0])
flask_jwt_extended.exceptions.NoAuthorizationError: Missing Authorization Header
